import React, { createContext, useState, useContext, ReactNode } from 'react';

export enum Language {
  ENGLISH = 'en',
  HINDI = 'hi',
  PUNJABI = 'pa',
  TAMIL = 'ta',
  MARATHI = 'mr'
}

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  [Language.ENGLISH]: {
    'nav.home': 'Home',
    'nav.donate': 'Donate',
    'nav.request': 'Receive',
    'nav.ngo': 'Partner',
    'nav.gov': 'Government',
    'nav.about': 'About',
    'nav.translate': 'Translate',
    'nav.signin': 'Sign In',
    'nav.getstarted': 'Get Started',
    'nav.logout': 'Logout',
    'hero.badge': 'India’s Smart Medicine Redistribution Network',
    'hero.title': 'Turn Your Unused Medicines Into Life-Saving Resources',
    'hero.desc': 'MedRoute connects surplus verified medicines from donors to patients who need them most. Fast, transparent, and completely free.',
    'hero.donate': 'Donate medicines',
    'hero.request': 'Request medicines',
    'hero.partner': 'Become a partner',
    'stats.saved': 'Medicines Saved (units)',
    'stats.lives': 'Lives Impacted',
    'stats.co2': 'CO₂ Reduced (kg)',
    'stats.waste': 'Waste Prevented (₹)',
    'hub.title': 'Hub Network',
    'hub.desc': 'Explore our network of hubs and dropboxes across India.',
    'hub.zoom': 'Zoom in to discover local collection points',
    'hub.search.title': 'Locate verified hubs',
    'hub.search.desc': 'Find nearest drop-boxes or clinics in your specific area.',
    'hub.search.placeholder': 'Enter area (e.g., Gandhi Nagar, Jammu)',
    'hub.search.find': 'Find',
    'hub.search.searching': 'Searching...',
    'hub.search.noResults': 'No results found for that area.',
    'hub.search.verified': 'Verified Hub',
    'hub.search.mapsLink': 'Search Maps for location',
    'map.title': 'Live Medicine Distribution Network',
    'map.desc': 'Track real-time medicine flows, drop-box locations, and active delivery routes across the city',
    'map.dropbox': 'Drop-box Locations',
    'map.routes': 'Active Routes',
    'map.delivered': 'Delivered Today',
    'how.title': 'How It Works',
    'how.desc': 'Simple, transparent, and efficient medicine redistribution in three steps',
    'how.step1.title': 'Collect',
    'how.step1.desc': 'Donors drop off unused medicines at verified collection points or schedule home pickup. Every donation is tracked and recorded.',
    'how.step2.title': 'Verify',
    'how.step2.desc': 'Our licensed pharmacists and verified systems perform a rigorous clinical audit on every batch to ensure absolute safety and authenticity.',
    'how.step3.title': 'Redirect',
    'how.step3.desc': 'Medicines are redistributed to verified NGOs, clinics, and patients in need through our secure logistics network.',
    'cta.title': 'Join the Life-saving Grid',
    'cta.desc': "Don't let medicines go to waste. Join thousands making healthcare accessible for all.",
    'cta.start': 'Start donating now',
    'cta.learn': 'Learn more',
    'auth.welcome': 'Welcome Back!',
    'auth.join': 'Join the Grid',
    'auth.loginDesc': 'To keep connected with us please login with your personal info',
    'auth.regDesc': 'Enter your personal details and start journey with us',
    'auth.create': 'Create Account',
    'auth.signin': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.google': 'Sign in with Google',
    'auth.emailOr': 'or use your email for',
    'auth.login': 'login',
    'auth.registration': 'registration',
    'auth.identity': 'Select Identity',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.remember': 'Remember me',
    'auth.forgot': 'Forgot password?',
    'auth.back': 'Back to Home',
    'donor.title': 'Donor Dashboard',
    'donor.subtitle': 'Track your impact and manage your donations',
    'donor.donate': 'Donate Medicine',
    'donor.history': 'Donation History',
    'donor.impact': 'Your Impact',
    'donor.saved': 'Medicines Saved',
    'donor.lives': 'Lives Impacted',
    'donor.points': 'MedPoints Earned',
    'receiver.title': 'Request Center',
    'receiver.subtitle': 'Verified pharmaceutical surplus available for those in need.',
    'receiver.newRequest': 'New Medicine Request',
    'receiver.log': 'Your Health Log',
    'receiver.ayushman': 'Validate Ayushman ID',
    'receiver.ayushmanPlaceholder': 'Enter Ayushman ID (e.g. ABC)',
    'receiver.validate': 'Validate Account',
    'receiver.invalidId': 'Invalid Ayushman ID. Please use "ABC" for prototype simulation.',
    'receiver.uploadPrescription': 'Upload Prescription',
    'receiver.prescriptionDesc': 'Please upload your medical prescription for verification.',
    'receiver.verifying': 'Verifying Prescription...',
    'receiver.verified': 'Verified Prescription',
    'receiver.verifiedDesc': 'Your prescription has been verified. You can now schedule delivery.',
    'receiver.schedule': 'Schedule Delivery',
    'receiver.scheduling': 'Scheduling Delivery...',
    'receiver.scheduled': 'Delivery Scheduled',
    'receiver.arrival': 'Estimated Arrival',
    'receiver.otp': 'Delivery OTP',
    'receiver.otpDesc': 'Show this OTP to the delivery partner.',
    'receiver.history': 'Previous Requests',
    'receiver.status.uploaded': 'Prescription Uploaded',
    'receiver.status.verified': 'Verified Prescription',
    'receiver.status.scheduled': 'Delivery Scheduled',
    'receiver.status.completed': 'Completed',
    'about.hero.part1': 'Every verified medicine redistributed is a step toward a ',
    'about.hero.part2': 'stronger, healthier India.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc1': 'To reduce pharmaceutical waste and ensure that surplus medicines reach those who truly need them through a ',
    'about.mission.desc2': 'transparent, efficient, and technology-driven',
    'about.mission.desc3': ' redistribution network.',
    'about.final.part1': 'Let’s come together to make healthcare more ',
    'about.final.part2': 'accessible, sustainable,',
    'about.final.part3': ' and impactful for every life.',
    'auth.invalidCredentials': 'Invalid credentials. Please register if you haven\'t yet.',
    'auth.accountCreated': 'Account created! A welcome email has been sent to your inbox.',
    'auth.roles.donor': 'Donor',
    'auth.roles.receiver': 'Receiver',
    'auth.roles.ngo': 'NGO Partner',
    'auth.roles.admin': 'Administrator',
    // Admin Landing
    'gov.portal': 'Admin Portal',
    'gov.restricted': 'Restricted access for admins only.',
    'gov.securePin': 'Secure Access PIN',
    'gov.invalidPin': 'Invalid authorization credentials. Access denied.',
    'gov.verifyIdentity': 'Verify Identity',
    'gov.returnPublic': 'Return to Public Site',
    'gov.emergencyAccess': 'Emergency Access Required',
    'gov.emergencyPin': 'Enter Emergency PIN',
    'gov.activate': 'Activate',
    'gov.forGov': 'For Administrators & Oversight',
    'gov.hero.title1': 'Data-Driven Transparency for ',
    'gov.hero.title2': 'Healthcare Policy',
    'gov.hero.desc': 'Real-time insights, complete traceability, and evidence-based policy making for pharmaceutical redistribution.',
    'gov.resume': 'Resume Operations',
    'gov.freeze': 'Freeze All Deliveries & Requests',
    'gov.getReports': 'Get Detailed Reports',
    'gov.exitEmergency': 'Exit Emergency Mode',
    'gov.activateEmergency': 'Activate Emergency Mode',
    'gov.networkMap': 'National Redistribution Network',
    'gov.networkDesc': 'Complete visibility into pharmaceutical redistribution across India.',
    'gov.realtimeMonitoring': 'Real-time transit monitoring & delivery confirmation',
    'gov.emergencyGrid': 'Emergency Response Grid',
    'gov.emergencyDesc': 'Prioritized pharmaceutical distribution in critical zones.',
    'gov.openImpactAudit': 'Open Emergency Impact Audit',
    'gov.emergencyActive': 'EMERGENCY MODE ACTIVE',
    'gov.activeZones': 'Active Disaster Zones',
    'gov.dbFeatures.title': 'Admin Dashboard Features',
    'gov.dbFeatures.desc': 'Comprehensive oversight and monitoring tools',
    'gov.dbFeatures.mapping': 'Geographic Mapping',
    'gov.dbFeatures.mappingDesc': 'Real-time district-wise donation and distribution heatmaps with demographic overlays.',
    'gov.dbFeatures.audit': 'Transaction Audit',
    'gov.dbFeatures.auditDesc': 'Complete traceability with batch IDs, timestamps, and verification logs.',
    'gov.dbFeatures.analytics': 'Analytics & Reports',
    'gov.dbFeatures.analyticsDesc': 'Monthly trends, waste reduction metrics, and carbon footprint analysis.',
    'gov.dbFeatures.emergency': 'Emergency Mode',
    'gov.dbFeatures.emergencyDesc': 'Disaster response coordination with priority routing and urgent supply tracking.',
    'gov.dbFeatures.stakeholders': 'Stakeholder Network',
    'gov.dbFeatures.stakeholdersDesc': 'Directory of verified donors, NGOs, and healthcare providers.',
    'gov.dbFeatures.api': 'Open Data API',
    'gov.dbFeatures.apiDesc': 'Developer access to anonymized data for research and policy analysis.',
    'gov.transparency.title': 'Complete Transparency',
    'gov.transparency.desc': 'Every transaction tracked from source to destination',
    'gov.transparency.tracking': 'Batch-Level Tracking',
    'gov.transparency.trackingDesc': 'Each medicine batch has unique ID, expiry date, verification status, donor details, and final beneficiary information.',
    'gov.transparency.optimization': 'Route Optimization',
    'gov.transparency.optimizationDesc': 'AI-powered logistics to minimize delivery time and carbon footprint with real-time tracking.',
    'gov.transparency.verification': 'Multi-Point Verification',
    'gov.transparency.verificationDesc': 'Licensed pharmacist verification at collection, storage, and distribution points with digital signatures.',
    'gov.transparency.immutable': 'Immutable Records',
    'gov.transparency.immutableDesc': 'Blockchain-backed audit trails ensuring data integrity and preventing tampering.',
    'gov.metrics.title': 'Policy Impact Metrics',
    'gov.metrics.desc': 'Evidence-based insights for healthcare policy',
    'gov.metrics.waste': 'Pharmaceutical Waste Prevented (Annual)',
    'gov.metrics.co2': 'CO₂ Emissions Reduced (Annual)',
    'gov.metrics.citizens': 'Citizens Served (Annual)',
    'gov.metrics.facilities': 'Healthcare Facilities Participating',
    'gov.compliance.title': 'Regulatory Compliance',
    'gov.compliance.desc': 'Fully compliant with national and international standards',
    'gov.compliance.act': 'Drugs and Cosmetics Act, 1940',
    'gov.compliance.actDesc': 'Full compliance with pharmaceutical regulations.',
    'gov.compliance.cdsco': 'Central Drugs Standard Control Organization',
    'gov.compliance.cdscoDesc': 'CDSCO approved processes and protocols.',
    'gov.compliance.iso': 'ISO 9001:2015 Quality Management',
    'gov.compliance.isoDesc': 'International quality standards certified.',
    'gov.compliance.it': 'IT Act 2000 & Data Protection',
    'gov.compliance.itDesc': 'Secure data handling and privacy protection.',
    'gov.compliance.env': 'Environmental Protection Act',
    'gov.compliance.envDesc': 'Eco-friendly waste reduction initiatives.',
    'gov.compliance.gdp': 'Good Distribution Practices (GDP)',
    'gov.compliance.gdpDesc': 'WHO-recommended distribution standards.',
    'gov.useCases.title': 'Admin Use Cases',
    'gov.useCases.disaster': 'Disaster Response Coordination',
    'gov.useCases.disasterDesc': 'During floods, earthquakes, or pandemics, activate emergency mode to:',
    'gov.useCases.disasterItem1': 'Identify disaster-affected zones requiring urgent medicine supply',
    'gov.useCases.disasterItem2': 'Prioritize critical medications (antibiotics, pain relief, chronic care)',
    'gov.useCases.disasterItem3': 'Coordinate with NGOs and mobile health units for rapid deployment',
    'gov.useCases.disasterItem4': 'Track real-time fulfillment rates and identify supply gaps',
    'gov.useCases.planning': 'Public Health Planning',
    'gov.useCases.planningDesc': 'Use aggregated data for evidence-based policy making:',
    'gov.useCases.planningItem1': 'Identify districts with medicine shortage patterns',
    'gov.useCases.planningItem2': 'Optimize public health program budgets and resource allocation',
    'gov.useCases.planningItem3': 'Monitor chronic disease prevalence through medicine request data',
    'gov.useCases.planningItem4': 'Evaluate impact of healthcare initiatives on underserved communities',
    // NGO Landing
    'ngo.forNgo': 'For NGOs & Healthcare Providers',
    'ngo.hero.title1': 'Partner With Us to Scale ',
    'ngo.hero.title2': 'Your Impact',
    'ngo.hero.desc': 'Access verified medicines, streamline distribution, and serve more communities through our transparent network.',
    'ngo.becomePartner': 'Become a Partner',
    'ngo.whoTitle': 'Who Can Partner With MedRoute?',
    'ngo.whoDesc': 'Organizations committed to healthcare access',
    'ngo.benefitTitle': 'Partnership Benefits',
    'ngo.benefitDesc': 'Why organizations choose MedRoute',
    'ngo.ready': 'Ready to Join Our Network?',
    'ngo.ctaDesc': 'Partner with MedRoute and amplify your healthcare impact across communities',
    'ngo.apply': 'Apply for Partnership',
    'ngo.who.orgs': 'NGOs & Charities',
    'ngo.who.orgsDesc': 'Non-profit organizations working in healthcare, poverty alleviation, or community welfare programs.',
    'ngo.who.clinics': 'Community Clinics',
    'ngo.who.clinicsDesc': 'Rural health centers, free clinics, and community health programs serving underserved populations.',
    'ngo.who.workers': 'Healthcare Workers',
    'ngo.who.workersDesc': 'Medical camps, mobile health units, and frontline healthcare workers in remote areas.',
    'ngo.benefit.verified': 'Verified Medicines',
    'ngo.benefit.verifiedDesc': 'All medicines verified by licensed pharmacists for safety and quality',
    'ngo.benefit.logistics': 'Free Logistics',
    'ngo.benefit.logisticsDesc': 'No-cost delivery to your distribution centers across the country',
    'ngo.benefit.tracking': 'Real-Time Tracking',
    'ngo.benefit.trackingDesc': 'Monitor inventory, deliveries, and impact metrics on your dashboard',
    'ngo.benefit.docs': 'Documentation',
    'ngo.benefit.docsDesc': 'Automated invoices, receipts, and impact reports for donors',
    'ngo.benefit.compliance': 'Compliance',
    'ngo.benefit.complianceDesc': 'Full regulatory compliance and transparent audit trails',
    'ngo.benefit.network': 'Network Access',
    'ngo.benefit.networkDesc': 'Connect with 1000+ donors, hospitals, and pharma partners',
    'ngo.how.title': 'How It Works for Partners',
    'ngo.how.steps.register': 'Register & Verify',
    'ngo.how.steps.registerDesc': 'Submit NGO registration, certifications, and program details.',
    'ngo.how.steps.browse': 'Browse Inventory',
    'ngo.how.steps.browseDesc': 'Access real-time database of available verified medicines.',
    'ngo.how.steps.orders': 'Place Orders',
    'ngo.how.steps.ordersDesc': 'Request medicines based on your community needs.',
    'ngo.how.steps.track': 'Track & Distribute',
    'ngo.how.steps.trackDesc': 'Monitor delivery and distribute to beneficiaries.',
    'ngo.req.title': 'Partnership Requirements',
    'ngo.req.reg': 'Valid Registration',
    'ngo.req.regDesc': 'NGO registration (12A/80G), FCRA (if applicable), or healthcare facility license',
    'ngo.req.docs': 'Program Documentation',
    'ngo.req.docsDesc': 'Details of healthcare programs, beneficiary demographics, and distribution plans',
    'ngo.req.staff': 'Qualified Personnel',
    'ngo.req.staffDesc': 'Licensed pharmacist or healthcare professional on staff for medicine management',
    'ngo.req.reporting': 'Impact Reporting',
    'ngo.req.reportingDesc': 'Agreement to provide quarterly reports on medicine distribution and beneficiary impact',
    'ngo.stories.title': 'Partner Success Stories',
    'ngo.stories.medsRedistributed': 'medicines redistributed',
    'ngo.stories.patientsTreated': 'patients treated',
    'ngo.stories.coverageExpanded': 'coverage expanded',
    // Donor Landing
    'donor.forDonors': 'For Donors',
    'donor.hero.title1': 'Donate Medicines.',
    'donor.hero.title2': 'Save Lives.',
    'donor.hero.desc': 'Your unused medicines can bring hope to someone in need. A simple act of kindness can create a healthier tomorrow for our communities.',
    'donor.startNow': 'Donate Medicines',
    'donor.whoDonate': 'Who Can Donate?',
    'donor.everyoneDiff': 'Everyone can make a difference',
    'donor.who.individuals': 'Individuals',
    'donor.who.individuals.item1': 'Leftover prescription medicines',
    'donor.who.individuals.item2': 'Over-the-counter medications',
    'donor.who.individuals.item3': 'Vitamins & supplements',
    'donor.who.individuals.item4': 'First aid supplies',
    'donor.who.pharmacies': 'Pharmacies',
    'donor.who.pharmacies.item1': 'Near-expiry inventory',
    'donor.who.pharmacies.item2': 'Overstocked items',
    'donor.who.pharmacies.item3': 'Discontinued products',
    'donor.who.pharmacies.item4': 'Sample medications',
    'donor.who.hospitals': 'Hospitals',
    'donor.who.hospitals.item1': 'Surplus inventory',
    'donor.who.hospitals.item2': 'Patient leftover medicines',
    'donor.who.hospitals.item3': 'Unopened supplies',
    'donor.who.hospitals.item4': 'Bulk donations',
    'donor.howTo': 'How to Donate',
    'donor.simpleSafe': 'Simple, safe, and convenient donation process',
    'donor.how.steps.register': 'Register',
    'donor.how.steps.registerDesc': 'Create your free account and complete your donor profile.',
    'donor.how.steps.list': 'List Medicines',
    'donor.how.steps.listDesc': 'Upload details, scan barcodes, check expiry dates, and add quantities.',
    'donor.how.steps.method': 'Choose Method',
    'donor.how.steps.methodDesc': 'Drop at nearest hub or schedule a free pickup from your location.',
    'donor.how.steps.track': 'Track Impact',
    'donor.how.steps.trackDesc': 'Monitor your donation journey and the impact in real-time.',
    'donor.guidelines': 'Donation Guidelines',
    'donor.guidelines.subtitle': 'Help us maintain safety and quality for those in need',
    'donor.guide.accept': 'What We Accept',
    'donor.guide.accept.item1': 'Medicines with 3+ months until expiry',
    'donor.guide.accept.item2': 'Unopened and sealed packaging',
    'donor.guide.accept.item3': 'Prescription and OTC medications',
    'donor.guide.accept.item4': 'Vitamins, supplements, and first aid',
    'donor.guide.accept.item5': 'Medical supplies and equipment',
    'donor.guide.reject': "What We Don't Accept",
    'donor.guide.reject.item1': 'Expired medications (past expiry date)',
    'donor.guide.reject.item2': 'Opened or damaged packaging',
    'donor.guide.reject.item3': 'Controlled substances (narcotics)',
    'donor.guide.reject.item4': 'Compounded medications',
    'donor.guide.reject.item5': 'Injectable or temperature-sensitive drugs',
    'donor.benefits': 'Benefits of Donating',
    'donor.benefit.lives': 'Save Lives',
    'donor.benefit.livesDesc': 'Your donations directly help patients who can\'t afford medicines.',
    'donor.benefit.env': 'Protect Environment',
    'donor.benefit.envDesc': 'Reduce pharmaceutical waste and prevent environmental pollution.',
    'donor.benefit.tax': 'Get Tax Benefits',
    'donor.benefit.taxDesc': 'Receive donation receipts for tax deduction purposes.',
    'donor.ready': 'Ready to Make a Difference?',
    'donor.cta.desc': "Don't let valuable medicines go to waste. Start donating today and save lives.",
    'donor.createAccount': 'Create Donor Account',
    'donor.db.title': 'Donor Hub',
    'donor.db.subtitle': 'Real-time medicine redistribution terminal',
    'donor.db.reset': 'Reset Hub',
    'donor.db.scan': 'Instant Lens Scan',
    'donor.db.upload': 'Upload Record',
    'donor.db.launching': 'Fast Launching',
    'donor.db.syncing': 'Syncing Clinical Lens...',
    'donor.db.analyzing': 'Analyzing batch',
    'donor.db.consulting': 'Consulting AI Engine',
    'donor.db.tabletsIdentified': 'unopened tablets identified',
    'donor.db.expiry': 'Expiration Date',
    'donor.db.confirmCount': 'Confirm tablet count',
    'donor.db.correctQuantity': 'Is this the correct quantity of tablets?',
    'donor.db.scanAgain': 'Scan again',
    'donor.db.addToLedger': 'Add to ledger',
    'donor.db.schedulePickup': 'Schedule pickup now?',
    'donor.db.logisticsReady': 'Our logistics network is ready to collect your donation within 60 minutes.',
    'donor.db.yesSchedule': 'Yes, schedule pickup',
    'donor.db.dropNearby': 'Drop in a nearby dropbox',
    'donor.db.maybeLater': 'Maybe later',
    'donor.db.pickupAddress': 'Pickup Address',
    'donor.db.enterAddress': 'Enter your full pickup address...',
    'donor.db.useLocation': 'Use Current Location',
    'donor.db.locating': 'Locating...',
    'donor.db.confirmSchedule': 'Confirm & Schedule',
    'donor.db.back': 'Back',
    'donor.db.assigning': 'Assigning Courier',
    'donor.db.findingRider': 'Finding the nearest available rider in your grid...',
    'donor.db.scheduled': 'Pickup Scheduled',
    'donor.db.arrivalShortly': 'We will pick your donated medicines within a span of 2-3 days. The rider will give you a call. Thank you after reaching your location.',
    'donor.db.otpLabel': 'Receipt Number / OTP',
    'donor.db.giveOtp': 'Please give this number to the rider upon arrival.',
    'donor.db.thanks': 'Thank you for your donation!',
    'donor.db.trackHere': 'Track here',
    'donor.db.returnHub': 'Return to Hub',
    'donor.db.liveTracking': 'Live Tracking',
    'donor.db.truckFrom': 'Truck starting from',
    'donor.db.calculatingRoute': 'Calculating Best Road Route...',
    'donor.db.consultingMaps': 'Consulting Google Maps Engine',
    'donor.db.riderEnRoute': 'Rider En Route',
    'donor.db.estArrival': 'Estimated Arrival',
    'donor.db.status': 'Status',
    'donor.db.onTime': 'On Time',
    'donor.db.findDropboxes': 'Find Nearby Dropboxes',
    'donor.db.enterPincode': 'Enter Pincode or Area...',
    'donor.db.showNearby': 'Show Nearby Dropboxes',
    'donor.db.searchPlaceholder': 'Search by area or pincode...',
    'donor.db.activeDropboxes': 'Dropboxes active in your sector',
    'donor.db.gridIntel': 'Grid Intelligence',
    'donor.db.engineActive': 'AI Engine Active',
    'donor.db.engineOnline': 'Clinical engine online. Processing redistribution requests at peak efficiency.',
    'donor.db.saved': 'Medicines Saved',
    // Receiver Landing
    'receiver.forCitizens': 'For Citizens',
    'receiver.hero.title1': 'Access Life-Saving Medicines ',
    'receiver.hero.title2': 'When You Need Them Most',
    'receiver.hero.desc': 'Free or subsidized medicines for those who need them. No patient should go without essential medication.',
    'receiver.requestMeds': 'Request Medicines',
    'receiver.whoRequest': 'Who Can Request Medicines?',
    'receiver.servesEveryone': 'MedRoute serves everyone in need',
    'receiver.howToRequest': 'How to Request Medicines',
    'receiver.commonMeds': 'Commonly Available Medicines',
    'receiver.reqRequirements': 'Request Requirements',
    'receiver.faq': 'Frequently Asked Questions',
    'receiver.needHelp': "Need Medicines? We're Here to Help",
    'receiver.submitRequest': 'Submit Medicine Request',
    'receiver.who.individual': 'Individual Patients',
    'receiver.who.individualDesc': 'Anyone facing financial constraints, lacking insurance, or needing emergency medication. We prioritize those with a valid Ayushman ID for last-mile access.',
    'receiver.who.families': 'Families',
    'receiver.who.familiesDesc': 'Families struggling with chronic illness costs, multiple prescriptions, or unexpected medical emergencies.',
    'receiver.who.caregivers': 'Caregivers',
    'receiver.who.caregiversDesc': 'Caregivers managing medication needs for elderly parents, disabled family members, or dependents.',
    'receiver.how.steps.register': 'Register',
    'receiver.how.steps.registerDesc': 'Create your profile with basic information and verification.',
    'receiver.how.steps.submit': 'Submit Request',
    'receiver.how.steps.submitDesc': 'Upload prescription and specify medicines needed.',
    'receiver.how.steps.match': 'Get Matched',
    'receiver.how.steps.matchDesc': 'Our system finds available medicines from verified donors.',
    'receiver.how.steps.receive': 'Receive',
    'receiver.how.steps.receiveDesc': 'Pick up from nearest hub or get home delivery.',
    'receiver.how.steps.desc': 'Simple 4-step process to get the medicines you need',
    'receiver.available.chronic': 'Chronic Care',
    'receiver.available.chronicDesc': 'Diabetes, Hypertension, Asthma',
    'receiver.available.antibiotics': 'Antibiotics',
    'receiver.available.antibioticsDesc': 'Common Infections, Respiratory',
    'receiver.available.pain': 'Pain Relief',
    'receiver.available.painDesc': 'Analgesics, Anti-inflammatory',
    'receiver.available.general': 'General Health',
    'receiver.available.generalDesc': 'Vitamins, Supplements, First Aid',
    'receiver.req.prescription': 'Valid Prescription',
    'receiver.req.prescriptionDesc': 'For prescription medicines, a valid doctor\'s prescription is required (can be uploaded as photo or PDF)',
    'receiver.req.identity': 'Identity Verification',
    'receiver.req.identityDesc': 'Basic identity verification to ensure medicines reach genuine beneficiaries (Aadhaar, PAN, or other ID)',
    'receiver.req.need': 'Medical Need Documentation',
    'receiver.req.needDesc': 'Brief explanation of medical condition and financial need (optional but helps prioritize urgent cases)',
    'receiver.faq.q1': 'Is there any cost for requesting medicines?',
    'receiver.faq.a1': 'No, our service is completely free. Some medicines may have minimal processing or delivery charges, but we work to keep costs as low as possible for everyone.',
    'receiver.faq.q2': 'How long does it take to receive medicines?',
    'receiver.faq.a2': 'Typically 2-5 days depending on availability and your location. Emergency requests are prioritized and can be fulfilled within 24-48 hours.',
    'receiver.faq.q3': 'Are the medicines safe and verified?',
    'receiver.faq.a3': 'Yes, all donated medicines are verified by licensed pharmacists for expiry dates, packaging integrity, and authenticity before redistribution.',
    'receiver.faq.q4': 'Can I request medicines for my family members?',
    'receiver.faq.a4': 'Yes, you can request on behalf of family members with their valid prescriptions and consent.',
    'receiver.cta.desc': 'No one should go without essential medication. Request what you need today.',
    'receiver.db.title': 'Request Center',
    'receiver.db.subtitle': 'Manage your medicine requests',
    'receiver.db.ayushmanPrompt': 'Let\'s start with your identity. Please validate your Ayushman Bharat ID to access the network.',
    'receiver.db.prescriptionPrompt': 'Identity verified. Now, please upload your clinical prescription for the required medicines.',
    'receiver.db.deliveryPrompt': 'Prescription verified. You can now schedule your delivery.',
    'receiver.db.activeSessions': 'Active Sessions',
    'receiver.db.gridStatus': 'Grid Status',
    'receiver.db.online': 'Online',
    'receiver.db.fulfillment': 'Fulfillment Active',
    'receiver.db.clinicalAudit': 'Consulting Clinical Audit Engine',
    'receiver.db.cancel': 'Cancel',
    'receiver.db.selectFile': 'Select File',
    'receiver.db.liveSync': 'Live Network Sync',
    'receiver.db.noRequests': 'No Active Requests',
    'receiver.db.historyDesc': 'Your medicine requests and history will appear here once you start a new request.',
    'receiver.db.networkLogistics': 'Network Logistics',
    'receiver.db.verificationNotice': 'The MedRoute system ensures clinical verification of every batch before it reaches you.',
    'receiver.db.systemStatus': 'System Status',
    'receiver.db.operational': 'Operational',
    'receiver.db.optimization': 'Logistics Path Optimization',
    'receiver.db.dijkstraDesc': 'Using Dijkstra\'s algorithm to find the most efficient delivery route from Donor to Receiver via Central Warehouse.',
    'receiver.db.safetyAssurance': 'Safety Assurance',
    'receiver.db.aiVerification': 'AI Verification',
    'receiver.db.aiVerificationDesc': 'Scanned via MedRoute Lens for authenticity.',
    'receiver.db.physicalCheck': 'Physical Check',
    'receiver.db.physicalCheckDesc': 'Inspected by licensed pharmacists at hubs.',
    'receiver.db.secureLogistics': 'Secure Logistics',
    'receiver.db.secureLogisticsDesc': 'Distributed via climate-controlled network.',
    'receiver.db.trackLive': 'Track Live Delivery',
    'receiver.db.backDashboard': 'Back to Dashboard',
    'receiver.db.rider': 'Rider',
    'receiver.db.verifiedPartner': 'Verified Partner',
    'receiver.db.call': 'Call',
    'receiver.db.orderReceived': 'Order Received',
    'receiver.db.movingTowards': 'Rider is moving towards you',
    'receiver.db.enjoyHealth': 'Enjoy your health',
  },
  [Language.HINDI]: {
    'nav.home': 'होम',
    'nav.donate': 'दान करें',
    'nav.request': 'अनुरोध',
    'nav.ngo': 'एनजीओ पोर्टल',
    'nav.gov': 'प्रशासक',
    'nav.about': 'हमारे बारे में',
    'nav.translate': 'अनुवाद',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'शुरू करें',
    'nav.logout': 'लॉगआउट',
    'hero.badge': 'स्मार्ट मेडिसिन पुनर्वितरण नेटवर्क',
    'hero.title': 'अप्रयुक्त दवाओं को जीवन रक्षक संसाधनों में बदलना',
    'hero.desc': 'फार्मास्युटिकल कचरे को कम करने, जीवन बचाने और बुद्धिमान दवा पुनर्वितरण के माध्यम से एक स्थायी स्वास्थ्य सेवा पारिस्थितिकी तंत्र बनाने के लिए हमारे नेटवर्क में शामिल हों।',
    'hero.donate': 'दवा दान करें',
    'hero.request': 'दवाओं का अनुरोध करें',
    'hero.partner': 'पार्टनर बनें',
    'stats.saved': 'बचाई गई दवाएं (यूनिट)',
    'stats.lives': 'प्रभावित जीवन',
    'stats.co2': 'CO₂ कम हुआ (किग्रा)',
    'stats.waste': 'बचाया गया कचरा (₹)',
    'map.title': 'लाइव मेडिसिन वितरण नेटवर्क',
    'map.desc': 'शहर भर में रीयल-टाइम दवा प्रवाह, ड्रॉप-बॉक्स स्थानों और सक्रिय वितरण मार्गों को ट्रैक करें',
    'map.dropbox': 'ड्रॉप-बॉक्स स्थान',
    'map.routes': 'सक्रिय मार्ग',
    'map.delivered': 'आज वितरित',
    'how.title': 'यह कैसे काम करता है',
    'how.desc': 'तीन चरणों में सरल, पारदर्शी और कुशल दवा पुनर्वितरण',
    'how.step1.title': 'संग्रह',
    'how.step1.desc': 'दाता अप्रयुक्त दवाओं को सत्यापित संग्रह बिंदुओं पर छोड़ते हैं या होम पिकअप शेड्यूल करते हैं। हर दान को ट्रैक और रिकॉर्ड किया जाता है।',
    'how.step2.title': 'सत्यापन',
    'how.step2.desc': 'हमारे लाइसेंस प्राप्त फार्मासिस्ट और सत्यापित सिस्टम पूर्ण सुरक्षा और प्रामाणिकता सुनिश्चित करने के लिए हर बैच पर कठोर नैदानिक ऑडिट करते हैं।',
    'how.step3.title': 'पुनर्निर्देशन',
    'how.step3.desc': 'दवाओं को हमारे सुरक्षित रसद नेटवर्क के माध्यम से सत्यापित एनजीओ, क्लीनिकों और जरूरतमंद मरीजों को पुनर्वितरित किया जाता है।',
    'cta.title': 'जीवन रक्षक ग्रिड में शामिल हों',
    'cta.desc': 'दवाओं को बर्बाद न होने दें। सभी के लिए स्वास्थ्य सेवा को सुलभ बनाने वाले हजारों लोगों में शामिल हों।',
    'cta.start': 'अभी दान करना शुरू करें',
    'cta.learn': 'अधिक जानें',
    'auth.welcome': 'वापसी पर स्वागत है!',
    'auth.join': 'ग्रिड में शामिल हों',
    'auth.loginDesc': 'हमसे जुड़े रहने के लिए कृपया अपनी व्यक्तिगत जानकारी के साथ लॉगिन करें',
    'auth.regDesc': 'अपना व्यक्तिगत विवरण दर्ज करें और हमारे साथ यात्रा शुरू करें',
    'auth.create': 'खाता बनाएं',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.google': 'गूगल के साथ साइन इन करें',
    'auth.emailOr': 'या ईमेल का उपयोग करें',
    'auth.login': 'लॉगिन',
    'auth.registration': 'पंजीकरण',
    'auth.identity': 'पहचान चुनें',
    'auth.email': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.remember': 'मुझे याद रखें',
    'auth.forgot': 'पासवर्ड भूल गए?',
    'auth.back': 'होम पर वापस जाएं',
    'donor.title': 'दाता डैशबोर्ड',
    'donor.subtitle': 'अपने प्रभाव को ट्रैक करें और अपने दान प्रबंधित करें',
    'donor.donate': 'दवा दान करें',
    'donor.history': 'दान इतिहास',
    'donor.impact': 'आपका प्रभाव',
    'donor.saved': 'बचाई गई दवाएं',
    'donor.lives': 'प्रभावित जीवन',
    'donor.points': 'मेडपॉइंट्स अर्जित',
    'receiver.title': 'अनुरोध केंद्र',
    'receiver.subtitle': 'जरूरतमंदों के लिए सत्यापित फार्मास्युटिकल अधिशेष उपलब्ध है।',
    'receiver.newRequest': 'नया दवा अनुरोध',
    'receiver.log': 'आपका स्वास्थ्य लॉग',
    'receiver.ayushman': 'आयुष्मान आईडी सत्यापित करें',
    'receiver.ayushmanPlaceholder': 'आयुष्मान आईडी दर्ज करें (जैसे ABC)',
    'receiver.validate': 'खाता सत्यापित करें',
    'receiver.invalidId': 'अमान्य आयुष्मान आईडी। कृपया प्रोटोटाइप सिमुलेशन के लिए "ABC" का उपयोग करें।',
    'receiver.uploadPrescription': 'प्रिस्क्रिप्शन अपलोड करें',
    'receiver.prescriptionDesc': 'कृपया सत्यापन के लिए अपना मेडिकल प्रिस्क्रिप्शन अपलोड करें।',
    'receiver.verifying': 'प्रिस्क्रिप्शन सत्यापित किया जा रहा है...',
    'receiver.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.verifiedDesc': 'आपका प्रिस्क्रिप्शन सत्यापित हो गया है। अब आप डिलीवरी शेड्यूल कर सकते हैं।',
    'receiver.schedule': 'डिलीवरी शेड्यूल करें',
    'receiver.scheduling': 'डिलीवरी शेड्यूल की जा रही है...',
    'receiver.scheduled': 'डिलीवरी शेड्यूल की गई',
    'receiver.arrival': 'अनुमानित आगमन',
    'receiver.otp': 'डिलीवरी ओटीपी',
    'receiver.otpDesc': 'डिलीवरी पार्टनर को यह ओटीपी दिखाएं।',
    'receiver.history': 'पिछले अनुरोध',
    'receiver.status.uploaded': 'प्रिस्क्रिप्शन अपलोड किया गया',
    'receiver.status.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.status.scheduled': 'डिलीवरी शेड्यूल की गई',
    'receiver.status.completed': 'पूरा हुआ',
    'about.hero.part1': 'प्रत्येक सत्यापित दवा का पुनर्वितरण एक ',
    'about.hero.part2': 'मजबूत, स्वस्थ भारत की ओर एक कदम है।',
    'about.mission.title': 'हमारा मिशन',
    'about.mission.desc1': 'दवाओं की बर्बादी को कम करना और यह सुनिश्चित करना कि अतिरिक्त दवाएं एक ',
    'about.mission.desc2': 'पारदर्शी, कुशल और तकनीक-संचालित',
    'about.mission.desc3': ' पुनर्वितरण नेटवर्क के माध्यम से उन लोगों तक पहुंचे जिन्हें वास्तव में उनकी आवश्यकता है।',
    'about.final.part1': 'आइए हम सब मिलकर स्वास्थ्य सेवा को हर जीवन के लिए अधिक ',
    'about.final.part2': 'सुलभ, टिकाऊ',
    'about.final.part3': ' और प्रभावशाली बनाने के लिए एक साथ आएं।',
    'about.cta': 'यात्रा शुरू करें',
    // Gov Landing
    'gov.portal': 'सरकारी पोर्टल',
    'gov.restricted': 'केवल अधिकृत कर्मियों के लिए प्रतिबंधित पहुंच।',
    'gov.securePin': 'सुरक्षित एक्सेस पिन',
    'gov.invalidPin': 'अमान्य प्राधिकरण क्रेडेंशियल। पहुंच अस्वीकार।',
    'gov.verifyIdentity': 'पहचान सत्यापित करें',
    'gov.returnPublic': 'सार्वजनिक साइट पर लौटें',
    'gov.emergencyAccess': 'आपातकालीन पहुंच आवश्यक',
    'gov.emergencyPin': 'आपातकालीन पिन दर्ज करें',
    'gov.activate': 'सक्रिय करें',
    'gov.forGov': 'सरकार और नीति निर्माताओं के लिए',
    'gov.hero.title1': 'स्वास्थ्य नीति के लिए ',
    'gov.hero.title2': 'डेटा-संचालित पारदर्शिता',
    'gov.hero.desc': 'फार्मास्युटिकल पुनर्वितरण के लिए रीयल-टाइम अंतर्दृष्टि, पूर्ण पता लगाने की क्षमता और साक्ष्य-आधारित नीति निर्माण।',
    'gov.resume': 'परिचालन फिर से शुरू करें',
    'gov.freeze': 'सभी वितरण और अनुरोध फ्रीज करें',
    'gov.getReports': 'विस्तृत रिपोर्ट प्राप्त करें',
    'gov.exitEmergency': 'आपातकालीन मोड से बाहर निकलें',
    'gov.activateEmergency': 'आपातकालीन मोड सक्रिय करें',
    'gov.networkMap': 'राष्ट्रीय पुनर्वितरण नेटवर्क',
    'gov.networkDesc': 'पूरे भारत में फार्मास्युटिकल पुनर्वितरण में पूर्ण दृश्यता।',
    'gov.realtimeMonitoring': 'रीयल-टाइम ट्रांजिट निगरानी और वितरण पुष्टि',
    'gov.emergencyGrid': 'आपातकालीन प्रतिक्रिया ग्रिड',
    'gov.emergencyDesc': 'महत्वपूर्ण क्षेत्रों में प्राथमिकता प्राप्त फार्मास्युटिकल वितरण।',
    'gov.openImpactAudit': 'आपातकालीन प्रभाव ऑडिट खोलें',
    'gov.emergencyActive': 'आपातकालीन मोड सक्रिय',
    'gov.activeZones': 'सक्रिय आपदा क्षेत्र',
    // NGO Landing
    'ngo.forNgo': 'एनजीओ और स्वास्थ्य सेवा प्रदाताओं के लिए',
    'ngo.hero.title1': 'अपने प्रभाव को बढ़ाने के लिए ',
    'ngo.hero.title2': 'हमारे साथ पार्टनर बनें',
    'ngo.hero.desc': 'सत्यापित दवाओं तक पहुंचें, वितरण को सुव्यवस्थित करें, और हमारे पारदर्शी नेटवर्क के माध्यम से अधिक समुदायों की सेवा करें।',
    'ngo.becomePartner': 'पार्टनर बनें',
    'ngo.whoTitle': 'मेडरूट के साथ कौन पार्टनर बन सकता है?',
    'ngo.whoDesc': 'स्वास्थ्य सेवा पहुंच के लिए प्रतिबद्ध संगठन',
    'ngo.benefitTitle': 'साझेदारी के लाभ',
    'ngo.benefitDesc': 'संगठन मेडरूट को क्यों चुनते हैं',
    'ngo.ready': 'हमारे नेटवर्क में शामिल होने के लिए तैयार हैं?',
    'ngo.ctaDesc': 'मेडरूट के साथ पार्टनर बनें और समुदायों में अपने स्वास्थ्य सेवा प्रभाव को बढ़ाएं',
    'ngo.apply': 'साझेदारी के लिए आवेदन करें',
    // Donor Landing
    'donor.forDonors': 'दाताओं के लिए',
    'donor.hero.title1': 'अपनी अप्रयुक्त दवाओं को ',
    'donor.hero.title2': 'जीवन रक्षक संसाधनों में बदलें',
    'donor.hero.desc': 'आपके द्वारा दान की गई हर दवा एक जीवन बचा सकती है। बदलाव लाने वाले हजारों व्यक्तियों, फार्मेसियों और अस्पतालों में शामिल हों।',
    'donor.startNow': 'अभी दान करना शुरू करें',
    'donor.whoDonate': 'कौन दान कर सकता है?',
    'donor.everyoneDiff': 'हर कोई बदलाव ला सकता है',
    'donor.howTo': 'दान कैसे करें',
    'donor.simpleSafe': 'सरल, सुरक्षित और सुविधाजनक दान प्रक्रिया',
    'donor.guidelines': 'दान दिशानिर्देश',
    'donor.benefits': 'दान करने के लाभ',
    'donor.ready': 'बदलाव लाने के लिए तैयार हैं?',
    'donor.createAccount': 'दाता खाता बनाएं',
    // Receiver Landing
    'receiver.forCitizens': 'नागरिकों के लिए',
    'receiver.hero.title1': 'जीवन रक्षक दवाओं तक पहुंचें ',
    'receiver.hero.title2': 'जब आपको उनकी सबसे अधिक आवश्यकता हो',
    'receiver.hero.desc': 'उन लोगों के लिए मुफ्त या रियायती दवाएं जिन्हें उनकी आवश्यकता है। कोई भी मरीज आवश्यक दवा के बिना नहीं रहना चाहिए।',
    'receiver.requestMeds': 'दवाओं का अनुरोध करें',
    'receiver.whoRequest': 'दवाओं का अनुरोध कौन कर सकता है?',
    'receiver.servesEveryone': 'मेडरूट जरूरतमंद सभी की सेवा करता है',
    'receiver.howToRequest': 'दवाओं का अनुरोध कैसे करें',
    'receiver.commonMeds': 'आमतौर पर उपलब्ध दवाएं',
    'receiver.reqRequirements': 'अनुरोध आवश्यकताएं',
    'receiver.faq': 'अक्सर पूछे जाने वाले प्रश्न',
    'receiver.needHelp': 'दवाओं की आवश्यकता है? हम यहां मदद के लिए हैं',
    'receiver.submitRequest': 'दवा अनुरोध सबमिट करें'
  },
  [Language.PUNJABI]: {
    'nav.home': 'ਹੋਮ',
    'nav.donate': 'ਦਾਨ ਕਰੋ',
    'nav.request': 'ਬੇਨਤੀ',
    'nav.ngo': 'ਐਨਜੀਓ ਪੋਰਟਲ',
    'nav.gov': 'ਪ੍ਰਸ਼ਾਸਕ',
    'nav.about': 'ਬਾਰੇ',
    'nav.translate': 'ਅਨੁਵਾਦ',
    'nav.signin': 'ਸਾਈਨ ਇਨ',
    'nav.getstarted': 'ਸ਼ੁਰੂ ਕਰੋ',
    'nav.logout': 'ਲੌਗਆਉਟ',
    'hero.badge': 'ਸਮਾਰਟ ਮੈਡੀਸਨ ਮੁੜ ਵੰਡ ਨੈੱਟਵਰਕ',
    'hero.title': 'ਅਣਵਰਤੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਸਰੋਤਾਂ ਵਿੱਚ ਬਦਲਣਾ',
    'hero.desc': 'ਫਾਰਮਾਸਿਊਟੀਕਲ ਰਹਿੰਦ-ਖੂੰਹਦ ਨੂੰ ਘਟਾਉਣ, ਜਾਨਾਂ ਬਚਾਉਣ ਅਤੇ ਬੁੱਧੀਮਾਨ ਦਵਾਈਆਂ ਦੀ ਮੁੜ ਵੰਡ ਰਾਹੀਂ ਇੱਕ ਟਿਕਾਊ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਣਾਲੀ ਬਣਾਉਣ ਲਈ ਸਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।',
    'hero.donate': 'ਦਵਾਈ ਦਾਨ ਕਰੋ',
    'hero.request': 'ਦਵਾਈਆਂ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    'hero.partner': 'ਭਾਈਵਾਲ ਬਣੋ',
    'stats.saved': 'ਬਚਾਈਆਂ ਗਈਆਂ ਦਵਾਈਆਂ (ਯੂਨਿਟ)',
    'stats.lives': 'ਪ੍ਰਭਾਵਿਤ ਜੀਵਨ',
    'stats.co2': 'CO₂ ਘਟਾਇਆ (ਕਿਲੋ)',
    'stats.waste': 'ਰੋਕੀ ਗਈ ਰਹਿੰਦ-ਖੂੰਹਦ (ਭਾਰਤੀ ਰੁਪਏ)',
    'map.title': 'ਲਾਈਵ ਮੈਡੀਸਨ ਵੰਡ ਨੈੱਟਵਰਕ',
    'map.desc': 'ਪੂਰੇ ਸ਼ਹਿਰ ਵਿੱਚ ਰੀਅਲ-ਟਾਈਮ ਦਵਾਈਆਂ ਦੇ ਪ੍ਰਵਾਹ, ਡ੍ਰੌਪ-ਬਾਕਸ ਸਥਾਨਾਂ ਅਤੇ ਸਰਗਰਮ ਡਿਲੀਵਰੀ ਰੂਟਾਂ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ',
    'map.dropbox': 'ਡ੍ਰੌਪ-ਬਾਕਸ ਸਥਾਨ',
    'map.routes': 'ਸਰਗਰਮ ਰੂਟ',
    'map.delivered': 'ਅੱਜ ਡਿਲੀਵਰ ਕੀਤਾ ਗਿਆ',
    'how.title': 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    'how.desc': 'ਤਿੰਨ ਕਦਮਾਂ ਵਿੱਚ ਸਰਲ, ਪਾਰਦਰਸ਼ੀ ਅਤੇ ਕੁਸ਼ਲ ਦਵਾਈਆਂ ਦੀ ਮੁੜ ਵੰਡ',
    'how.step1.title': 'ਇਕੱਠਾ ਕਰਨਾ',
    'how.step1.desc': 'ਦਾਨੀ ਅਣਵਰਤੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ਪ੍ਰਮਾਣਿਤ ਸੰਗ੍ਰਹਿ ਬਿੰਦੂਆਂ ਤੇ ਛੱਡਦੇ ਹਨ ਜਾਂ ਹੋਮ ਪਿਕਅੱਪ ਤੈਅ ਕਰਦੇ ਹਨ। ਹਰ ਦਾਨ ਨੂੰ ਟ੍ਰੈਕ ਅਤੇ ਰਿਕਾਰਡ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।',
    'how.step2.title': 'ਪੜਤਾਲ',
    'how.step2.desc': 'ਸਾਡੇ ਲਾਇਸੰਸਸ਼ੁਦਾ ਫਾਰਮਾਸਿਸਟ ਅਤੇ ਪ੍ਰਮਾਣਿਤ ਸਿਸਟਮ ਪੂਰਨ ਸੁਰੱਖਿਆ ਅਤੇ ਪ੍ਰਮਾਣਿਕਤਾ ਨੂੰ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਹਰ ਬੈਚ ਤੇ ਸਖ਼ਤ ਕਲੀਨਿਕਲ ਆਡਿਟ ਕਰਦੇ ਹਨ।',
    'how.step3.title': 'ਮੁੜ ਵੰਡ',
    'how.step3.desc': 'ਦਵਾਈਆਂ ਸਾਡੇ ਸੁਰੱਖਿਅਤ ਲੌਜਿਸਟਿਕਸ ਨੈੱਟਵਰਕ ਰਾਹੀਂ ਪ੍ਰਮਾਣਿਤ ਐਨਜੀਓ, ਕਲੀਨਿਕਾਂ ਅਤੇ ਲੋੜਵੰਦ ਮਰੀਜ਼ਾਂ ਨੂੰ ਮੁੜ ਵੰਡੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।',
    'cta.title': 'ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਗਰਿੱਡ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'cta.desc': 'ਦਵਾਈਆਂ ਨੂੰ ਬਰਬਾਦ ਨਾ ਹੋਣ ਦਿਓ। ਸਾਰਿਆਂ ਲਈ ਸਿਹਤ ਸੰਭਾਲ ਨੂੰ ਸੁਲਭ ਬਣਾਉਣ ਵਾਲੇ ਹਜ਼ਾਰਾਂ ਲੋਕਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।',
    'cta.start': 'ਹੁਣੇ ਦਾਨ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
    'cta.learn': 'ਹੋਰ ਜਾਣੋ',
    'auth.welcome': 'ਜੀ ਆਇਆਂ ਨੂੰ!',
    'auth.join': 'ਗਰਿੱਡ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
    'auth.loginDesc': 'ਸਾਡੇ ਨਾਲ ਜੁੜੇ ਰਹਿਣ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀ ਨਿੱਜੀ ਜਾਣਕਾਰੀ ਨਾਲ ਲੌਗਇਨ ਕਰੋ',
    'auth.regDesc': 'ਆਪਣੇ ਨਿੱਜੀ ਵੇਰਵੇ ਦਰਜ ਕਰੋ ਅਤੇ ਸਾਡੇ ਨਾਲ ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    'auth.create': 'ਖਾਤਾ ਬਣਾਓ',
    'auth.signin': 'ਸਾਈਨ ਇਨ',
    'auth.signup': 'ਸਾਈਨ ਅੱਪ',
    'auth.google': 'ਗੂਗਲ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ',
    'auth.emailOr': 'ਜਾਂ ਈਮੇਲ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'auth.login': 'ਲੌਗਇਨ',
    'auth.registration': 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    'auth.identity': 'ਪਛਾਣ ਚੁਣੋ',
    'auth.email': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.remember': 'ਮੈਨੂੰ ਯਾਦ ਰੱਖੋ',
    'auth.forgot': 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    'auth.back': 'ਹੋਮ ਤੇ ਵਾਪਸ ਜਾਓ',
    'donor.title': 'ਦਾਨੀ ਡੈਸ਼ਬੋਰਡ',
    'donor.subtitle': 'ਆਪਣੇ ਪ੍ਰਭਾਵ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ ਅਤੇ ਆਪਣੇ ਦਾਨ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ',
    'donor.donate': 'ਦਵਾਈ ਦਾਨ ਕਰੋ',
    'donor.history': 'ਦਾਨ ਇਤਿਹਾਸ',
    'donor.impact': 'ਤੁਹਾਡਾ ਪ੍ਰਭਾਵ',
    'donor.saved': 'ਬਚਾਈਆਂ ਗਈਆਂ ਦਵਾਈਆਂ',
    'donor.lives': 'ਪ੍ਰਭਾਵਿਤ ਜੀਵਨ',
    'donor.points': 'ਮੈਡਪੁਆਇੰਟਸ ਕਮਾਏ',
    'receiver.title': 'ਬੇਨਤੀ ਕੇਂਦਰ',
    'receiver.subtitle': 'ਲੋੜਵੰਦਾਂ ਲਈ ਪ੍ਰਮਾਣਿਤ ਫਾਰਮਾਸਿਊਟੀਕਲ ਸਰਪਲੱਸ ਉਪਲਬਧ ਹੈ।',
    'receiver.newRequest': 'ਨਵੀਂ ਦਵਾਈ ਦੀ ਬੇਨਤੀ',
    'receiver.log': 'ਤੁਹਾਡਾ ਸਿਹਤ ਲੌਗ',
    'receiver.ayushman': 'ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ ਦੀ ਪੜਤਾਲ ਕਰੋ',
    'receiver.ayushmanPlaceholder': 'ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ ਦਰਜ ਕਰੋ (ਜਿਵੇਂ ABC)',
    'receiver.validate': 'ਖਾਤੇ ਦੀ ਪੜਤਾਲ ਕਰੋ',
    'receiver.invalidId': 'ਅਵੈਧ ਆਯੁਸ਼ਮਾਨ ਆਈਡੀ। ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰੋਟੋਟਾਈਪ ਸਿਮੂਲੇਸ਼ਨ ਲਈ "ABC" ਦੀ ਵਰਤੋਂ ਕਰੋ।',
    'receiver.uploadPrescription': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕਰੋ',
    'receiver.prescriptionDesc': 'ਕਿਰਪਾ ਕਰਕੇ ਪੜਤਾਲ ਲਈ ਆਪਣੀ ਮੈਡੀਕਲ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕਰੋ।',
    'receiver.verifying': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਦੀ ਪੜਤਾਲ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'receiver.verified': 'ਪ੍ਰਮਾਣਿਤ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ',
    'receiver.verifiedDesc': 'ਤੁਹਾਡੀ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਦੀ ਪੜਤਾਲ ਹੋ ਗਈ ਹੈ। ਹੁਣ ਤੁਸੀਂ ਡਿਲੀਵਰੀ ਤੈਅ ਕਰ ਸਕਦੇ ਹੋ।',
    'receiver.schedule': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕਰੋ',
    'receiver.scheduling': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...',
    'receiver.scheduled': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਗਈ',
    'receiver.arrival': 'ਅਨੁਮਾਨਿਤ ਆਗਮਨ',
    'receiver.otp': 'ਡਿਲੀਵਰੀ ਓਟੀਪੀ',
    'receiver.otpDesc': 'ਡਿਲੀਵਰੀ ਪਾਰਟਨਰ ਨੂੰ ਇਹ ਓਟੀਪੀ ਦਿਖਾਓ।',
    'receiver.history': 'ਪਿਛਲੀਆਂ ਬੇਨਤੀਆਂ',
    'receiver.status.uploaded': 'ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਅਪਲੋਡ ਕੀਤੀ ਗਈ',
    'receiver.status.verified': 'ਪ੍ਰਮਾਣਿਤ ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ',
    'receiver.status.scheduled': 'ਡਿਲੀਵਰੀ ਤੈਅ ਕੀਤੀ ਗਈ',
    'receiver.status.completed': 'ਪੂਰਾ ਹੋਇਆ',
    'about.hero.part1': 'ਹਰ ਪ੍ਰਮਾਣਿਤ ਦਵਾਈ ਦੀ ਮੁੜ ਵੰਡ ਇੱਕ ',
    'about.hero.part2': 'ਮਜ਼ਬੂਤ, ਸਿਹਤਮੰਦ ਭਾਰਤ ਵੱਲ ਇੱਕ ਕਦਮ ਹੈ।',
    'about.mission.title': 'ਸਾਡਾ ਮਿਸ਼ਨ',
    'about.mission.desc1': 'ਦਵਾਈਆਂ ਦੀ ਬਰਬਾਦੀ ਨੂੰ ਘਟਾਉਣਾ ਅਤੇ ਇਹ ਯਕੀਨੀ ਬਣਾਉਣਾ ਕਿ ਵਾਧੂ ਦਵਾਈਆਂ ਇੱਕ ',
    'about.mission.desc2': 'ਪਾਰਦਰਸ਼ੀ, ਕੁਸ਼ਲ ਅਤੇ ਤਕਨਾਲੋਜੀ-ਸੰਚਾਲਿਤ',
    'about.mission.desc3': ' ਮੁੜ ਵੰਡ ਨੈੱਟਵਰਕ ਰਾਹੀਂ ਉਹਨਾਂ ਲੋਕਾਂ ਤੱਕ ਪਹੁੰਚਣ ਜਿਨ੍ਹਾਂ ਨੂੰ ਸੱਚਮੁੱਚ ਉਹਨਾਂ ਦੀ ਲੋੜ ਹੈ।',
    'about.final.part1': 'ਆਓ ਅਸੀਂ ਸਾਰੇ ਮਿਲ ਕੇ ਸਿਹਤ ਸੰਭਾਲ ਨੂੰ ਹਰ ਜੀਵਨ ਲਈ ਵਧੇਰੇ ',
    'about.final.part2': 'ਸੁਲਭ, ਟਿਕਾਊ',
    'about.final.part3': ' ਅਤੇ ਪ੍ਰਭਾਵਸ਼ਾਲੀ ਬਣਾਉਣ ਲਈ ਇੱਕਠੇ ਹੋਈਏ।',
    'about.cta': 'ਯਾਤਰਾ ਸ਼ੁਰੂ ਕਰੋ',
    // Gov Landing
    'gov.portal': 'ਸਰਕਾਰੀ ਪੋਰਟਲ',
    'gov.restricted': 'ਸਿਰਫ ਅਧਿਕਾਰਤ ਕਰਮਚਾਰੀਆਂ ਲਈ ਪ੍ਰਤਿਬੰਧਿਤ ਪਹੁੰਚ।',
    'gov.securePin': 'ਸੁਰੱਖਿਅਤ ਐਕਸੈਸ ਪਿੰਨ',
    'gov.invalidPin': 'ਅਵੈਧ ਅਧਿਕਾਰ ਪ੍ਰਮਾਣ ਪੱਤਰ। ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ।',
    'gov.verifyIdentity': 'ਪਛਾਣ ਦੀ ਪੜਤਾਲ ਕਰੋ',
    'gov.returnPublic': 'ਜਨਤਕ ਸਾਈਟ ਤੇ ਵਾਪਸ ਜਾਓ',
    'gov.emergencyAccess': 'ਐਮਰਜੈਂਸੀ ਪਹੁੰਚ ਲੋੜੀਂਦੀ ਹੈ',
    'gov.emergencyPin': 'ਐਮਰਜੈਂਸੀ ਪਿੰਨ ਦਰਜ ਕਰੋ',
    'gov.activate': 'ਸਰਗਰਮ ਕਰੋ',
    'gov.forGov': 'ਸਰਕਾਰ ਅਤੇ ਨੀਤੀ ਨਿਰਮਾਤਾਵਾਂ ਲਈ',
    'gov.hero.title1': 'ਸਿਹਤ ਨੀਤੀ ਲਈ ',
    'gov.hero.title2': 'ਡਾਟਾ-ਸੰਚਾਲਿਤ ਪਾਰਦਰਸ਼ਤਾ',
    'gov.hero.desc': 'ਫਾਰਮਾਸਿਊਟੀਕਲ ਮੁੜ ਵੰਡ ਲਈ ਰੀਅਲ-ਟਾਈਮ ਸੂਝ, ਪੂਰੀ ਪਤਾ ਲਗਾਉਣ ਦੀ ਯੋਗਤਾ ਅਤੇ ਸਬੂਤ-ਅਧਾਰਤ ਨੀਤੀ ਨਿਰਮਾਣ।',
    'gov.resume': 'ਕਾਰਜ ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ',
    'gov.freeze': 'ਸਾਰੀਆਂ ਡਿਲੀਵਰੀ ਅਤੇ ਬੇਨਤੀਆਂ ਨੂੰ ਫ੍ਰੀਜ਼ ਕਰੋ',
    'gov.getReports': 'ਵਿਸਤ੍ਰਿਤ ਰਿਪੋਰਟਾਂ ਪ੍ਰਾਪਤ ਕਰੋ',
    'gov.exitEmergency': 'ਐਮਰਜੈਂਸੀ ਮੋਡ ਤੋਂ ਬਾਹਰ ਨਿਕਲੋ',
    'gov.activateEmergency': 'ਐਮਰਜੈਂਸੀ ਮੋਡ ਸਰਗਰਮ ਕਰੋ',
    'gov.networkMap': 'ਰਾਸ਼ਟਰੀ ਮੁੜ ਵੰਡ ਨੈੱਟਵਰਕ',
    'gov.networkDesc': 'ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਫਾਰਮਾਸਿਊਟੀਕਲ ਮੁੜ ਵੰਡ ਵਿੱਚ ਪੂਰੀ ਦਿੱਖ।',
    'gov.realtimeMonitoring': 'ਰੀਅਲ-ਟਾਈਮ ਟ੍ਰਾਂਜ਼ਿਟ ਨਿਗਰਾਨੀ ਅਤੇ ਡਿਲੀਵਰੀ ਦੀ ਪੁਸ਼ਟੀ',
    'gov.emergencyGrid': 'ਐਮਰਜੈਂਸੀ ਰਿਸਪਾਂਸ ਗਰਿੱਡ',
    'gov.emergencyDesc': 'ਨਾਜ਼ੁਕ ਖੇਤਰਾਂ ਵਿੱਚ ਤਰਜੀਹੀ ਫਾਰਮਾਸਿਊਟੀਕਲ ਵੰਡ।',
    'gov.openImpactAudit': 'ਐਮਰਜੈਂਸੀ ਪ੍ਰਭਾਵ ਆਡਿਟ ਖੋਲ੍ਹੋ',
    'gov.emergencyActive': 'ਐਮਰਜੈਂਸੀ ਮੋਡ ਸਰਗਰਮ ਹੈ',
    'gov.activeZones': 'ਸਰਗਰਮ ਆਫ਼ਤ ਖੇਤਰ',
    // NGO Landing
    'ngo.forNgo': 'ਐਨਜੀਓ ਅਤੇ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਦਾਤਾਵਾਂ ਲਈ',
    'ngo.hero.title1': 'ਆਪਣੇ ਪ੍ਰਭਾਵ ਨੂੰ ਵਧਾਉਣ ਲਈ ',
    'ngo.hero.title2': 'ਸਾਡੇ ਨਾਲ ਭਾਈਵਾਲ ਬਣੋ',
    'ngo.hero.desc': 'ਪ੍ਰਮਾਣਿਤ ਦਵਾਈਆਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰੋ, ਵੰਡ ਨੂੰ ਸੁਚਾਰੂ ਬਣਾਓ, ਅਤੇ ਸਾਡੇ ਪਾਰਦਰਸ਼ੀ ਨੈੱਟਵਰਕ ਰਾਹੀਂ ਹੋਰ ਭਾਈਚਾਰਿਆਂ ਦੀ ਸੇਵਾ ਕਰੋ।',
    'ngo.becomePartner': 'ਭਾਈਵਾਲ ਬਣੋ',
    'ngo.whoTitle': 'ਮੈਡਰੂਟ ਨਾਲ ਕੌਣ ਭਾਈਵਾਲ ਬਣ ਸਕਦਾ ਹੈ?',
    'ngo.whoDesc': 'ਸਿਹਤ ਸੰਭਾਲ ਪਹੁੰਚ ਲਈ ਵਚਨਬੱਧ ਸੰਸਥਾਵਾਂ',
    'ngo.benefitTitle': 'ਭਾਈਵਾਲੀ ਦੇ ਲਾਭ',
    'ngo.benefitDesc': 'ਸੰਸਥਾਵਾਂ ਮੈਡਰੂਟ ਕਿਉਂ ਚੁਣਦੀਆਂ ਹਨ',
    'ngo.ready': 'ਸਾਡੇ ਨੈੱਟਵਰਕ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਣ ਲਈ ਤਿਆਰ ਹੋ?',
    'ngo.ctaDesc': 'ਮੈਡਰੂਟ ਨਾਲ ਭਾਈਵਾਲ ਬਣੋ ਅਤੇ ਭਾਈਚਾਰਿਆਂ ਵਿੱਚ ਆਪਣੇ ਸਿਹਤ ਸੰਭਾਲ ਪ੍ਰਭਾਵ ਨੂੰ ਵਧਾਓ',
    'ngo.apply': 'ਭਾਈਵਾਲੀ ਲਈ ਅਰਜ਼ੀ ਦਿਓ',
    // Donor Landing
    'donor.forDonors': 'ਦਾਨੀਆਂ ਲਈ',
    'donor.hero.title1': 'ਆਪਣੀਆਂ ਅਣਵਰਤੀਆਂ ਦਵਾਈਆਂ ਨੂੰ ',
    'donor.hero.title2': 'ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੇ ਸਰੋਤਾਂ ਵਿੱਚ ਬਦਲੋ',
    'donor.hero.desc': 'ਤੁਹਾਡੇ ਦੁਆਰਾ ਦਾਨ ਕੀਤੀ ਗਈ ਹਰ ਦਵਾਈ ਇੱਕ ਜਾਨ ਬਚਾ ਸਕਦੀ ਹੈ। ਬਦਲਾਅ ਲਿਆਉਣ ਵਾਲੇ ਹਜ਼ਾਰਾਂ ਵਿਅਕਤੀਆਂ, ਫਾਰਮੇਸੀਆਂ ਅਤੇ ਹਸਪਤਾਲਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ।',
    'donor.startNow': 'ਹੁਣੇ ਦਾਨ ਕਰਨਾ ਸ਼ੁਰੂ ਕਰੋ',
    'donor.whoDonate': 'ਕੌਣ ਦਾਨ ਕਰ ਸਕਦਾ ਹੈ?',
    'donor.everyoneDiff': 'ਹਰ ਕੋਈ ਬਦਲਾਅ ਲਿਆ ਸਕਦਾ ਹੈ',
    'donor.howTo': 'ਦਾਨ ਕਿਵੇਂ ਕਰਨਾ ਹੈ',
    'donor.simpleSafe': 'ਸਰਲ, ਸੁਰੱਖਿਅਤ ਅਤੇ ਸੁਵਿਧਾਜਨਕ ਦਾਨ ਪ੍ਰਕਿਰਿਆ',
    'donor.guidelines': 'ਦਾਨ ਦਿਸ਼ਾਨਿਰਦੇਸ਼',
    'donor.benefits': 'ਦਾਨ ਕਰਨ ਦੇ ਲਾਭ',
    'donor.ready': 'ਬਦਲਾਅ ਲਿਆਉਣ ਲਈ ਤਿਆਰ ਹੋ?',
    'donor.createAccount': 'ਦਾਨੀ ਖਾਤਾ ਬਣਾਓ',
    // Receiver Landing
    'receiver.forCitizens': 'ਨਾਗਰਿਕਾਂ ਲਈ',
    'receiver.hero.title1': 'ਜੀਵਨ ਬਚਾਉਣ ਵਾਲੀਆਂ ਦਵਾਈਆਂ ਤੱਕ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰੋ ',
    'receiver.hero.title2': 'ਜਦੋਂ ਤੁਹਾਨੂੰ ਉਹਨਾਂ ਦੀ ਸਭ ਤੋਂ ਵੱਧ ਲੋੜ ਹੋਵੇ',
    'receiver.hero.desc': 'ਉਹਨਾਂ ਲੋਕਾਂ ਲਈ ਮੁਫਤ ਜਾਂ ਰਿਆਇਤੀ ਦਵਾਈਆਂ ਜਿਨ੍ਹਾਂ ਨੂੰ ਉਹਨਾਂ ਦੀ ਲੋੜ ਹੈ। ਕੋਈ ਵੀ ਮਰੀਜ਼ ਜ਼ਰੂਰੀ ਦਵਾਈ ਤੋਂ ਬਿਨਾਂ ਨਹੀਂ ਰਹਿਣਾ ਚਾਹੀਦਾ।',
    'receiver.requestMeds': 'ਦਵਾਈਆਂ ਦੀ ਬੇਨਤੀ ਕਰੋ',
    'receiver.whoRequest': 'ਦਵਾਈਆਂ ਦੀ ਬੇਨਤੀ ਕੌਣ ਕਰ ਸਕਦਾ ਹੈ?',
    'receiver.servesEveryone': 'ਮੈਡਰੂਟ ਜ਼ਰੂਰਤਮੰਦ ਸਭ ਦੀ ਸੇਵਾ ਕਰਦਾ ਹੈ',
    'receiver.howToRequest': 'ਦਵਾਈਆਂ ਦੀ ਬੇਨਤੀ ਕਿਵੇਂ ਕਰਨੀ ਹੈ',
    'receiver.commonMeds': 'ਆਮ ਤੌਰ ਤੇ ਉਪਲਬਧ ਦਵਾਈਆਂ',
    'receiver.reqRequirements': 'ਬੇਨਤੀ ਦੀਆਂ ਲੋੜਾਂ',
    'receiver.faq': 'ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ',
    'receiver.needHelp': 'ਦਵਾਈਆਂ ਦੀ ਲੋੜ ਹੈ? ਅਸੀਂ ਇੱਥੇ ਮਦਦ ਲਈ ਹਾਂ',
    'receiver.submitRequest': 'ਦਵਾਈ ਦੀ ਬੇਨਤੀ ਜਮ੍ਹਾਂ ਕਰੋ'
  },
  [Language.TAMIL]: {
    'nav.home': 'முகப்பு',
    'nav.donate': 'தானம் செய்',
    'nav.request': 'கோரிக்கை',
    'nav.ngo': 'என்ஜிஓ போர்டல்',
    'nav.gov': 'நிர்வாகம்',
    'nav.about': 'பற்றி',
    'nav.translate': 'மொழிபெயர்ப்பு',
    'nav.signin': 'உள்நுழைக',
    'nav.getstarted': 'தொடங்குங்கள்',
    'nav.logout': 'வெளியேறு',
    'hero.badge': 'ஸ்மார்ட் மருந்து மறுவிநியோக நெட்வொர்க்',
    'hero.title': 'பயன்படுத்தப்படாத மருந்துகளை உயிர் காக்கும் வளங்களாக மாற்றுதல்',
    'hero.desc': 'மருந்து கழிவுகளை குறைக்கவும், உயிர்களைக் காக்கவும், அறிவார்ந்த மருந்து மறுவிநியோகம் மூலம் நிலையான சுகாதார சுற்றுச்சூழல் அமைப்பை உருவாக்கவும் எங்கள் நெட்வொர்க்கில் இணையுங்கள்.',
    'hero.donate': 'மருந்து தானம் செய்யுங்கள்',
    'hero.request': 'மருந்துகளைக் கோருங்கள்',
    'hero.partner': 'கூட்டாளராகுங்கள்',
    'stats.saved': 'சேமிக்கப்பட்ட மருந்துகள் (அலகுகள்)',
    'stats.lives': 'பாதிக்கப்பட்ட உயிர்கள்',
    'stats.co2': 'CO₂ குறைக்கப்பட்டது (கிலோ)',
    'stats.waste': 'தடுக்கப்பட்ட கழிவு (₹)',
    'map.title': 'நேரடி மருந்து விநியோக நெட்வொர்க்',
    'map.desc': 'நகரம் முழுவதும் நிகழ்நேர மருந்து ஓட்டங்கள், டிராப்-பாக்ஸ் இடங்கள் மற்றும் செயலில் உள்ள விநியோக வழிகளைக் கண்காணிக்கவும்',
    'map.dropbox': 'டிராப்-பாக்ஸ் இடங்கள்',
    'map.routes': 'செயலில் உள்ள வழிகள்',
    'map.delivered': 'இன்று விநியோகிக்கப்பட்டது',
    'how.title': 'இது எப்படி வேலை செய்கிறது',
    'how.desc': 'மூன்று படிகளில் எளிமையான, வெளிப்படையான மற்றும் திறமையான மருந்து மறுவிநியோகம்',
    'how.step1.title': 'சேகரிப்பு',
    'how.step1.desc': 'நன்கொடையாளர்கள் பயன்படுத்தப்படாத மருந்துகளை சரிபார்க்கப்பட்ட சேகரிப்பு மையங்களில் ஒப்படைக்கிறார்கள் அல்லது வீட்டிலிருந்து எடுக்கும் நேரத்தை திட்டமிடுகிறார்கள். ஒவ்வொரு நன்கொடையும் கண்காணிக்கப்பட்டு பதிவு செய்யப்படுகிறது.',
    'how.step2.title': 'சரிபார்ப்பு',
    'how.step2.desc': 'எங்கள் உரிமம் பெற்ற மருந்தாளுநர்கள் மற்றும் சரிபார்க்கப்பட்ட அமைப்புகள் முழுமையான பாதுகாப்பு மற்றும் நம்பகத்தன்மையை உறுதிப்படுத்த ஒவ்வொரு தொகுப்பிலும் கடுமையான மருத்துவ தணிக்கையைச் செய்கின்றன.',
    'how.step3.title': 'மறுவிநியோகம்',
    'how.step3.desc': 'மருந்துகள் எங்கள் பாதுகாப்பான தளவாட நெட்வொர்க் மூலம் சரிபார்க்கப்பட்ட என்ஜிஓக்கள், கிளினிக்குகள் மற்றும் தேவைப்படும் நோயாளிகளுக்கு மறுவிநியோகம் செய்யப்படுகின்றன.',
    'cta.title': 'உயிர் காக்கும் கட்டமைப்பில் இணையுங்கள்',
    'cta.desc': 'மருந்துகளை வீணாக்காதீர்கள். அனைவருக்கும் சுகாதார சேவையை அணுகக்கூடியதாக மாற்றும் ஆயிரக்கணக்கான மக்களுடன் இணையுங்கள்.',
    'cta.start': 'இப்போதே தானம் செய்யத் தொடங்குங்கள்',
    'cta.learn': 'மேலும் அறிய',
    'auth.welcome': 'மீண்டும் வருக!',
    'auth.join': 'கட்டமைப்பில் இணையுங்கள்',
    'auth.loginDesc': 'எங்களுடன் இணைந்திருக்க உங்கள் தனிப்பட்ட தகவலுடன் உள்நுழையவும்',
    'auth.regDesc': 'உங்கள் தனிப்பட்ட விவரங்களை உள்ளிட்டு எங்களுடன் பயணத்தைத் தொடங்குங்கள்',
    'auth.create': 'கணக்கை உருவாக்கு',
    'auth.signin': 'உள்நுழைக',
    'auth.signup': 'பதிவு செய்க',
    'auth.google': 'கூகுள் மூலம் உள்நுழைக',
    'auth.emailOr': 'அல்லது மின்னஞ்சலைப் பயன்படுத்தவும்',
    'auth.login': 'உள்நுழைவு',
    'auth.registration': 'பதிவு',
    'auth.identity': 'அடையாளத்தைத் தேர்ந்தெடுக்கவும்',
    'auth.email': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.remember': 'என்னை நினைவில் கொள்',
    'auth.forgot': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'auth.back': 'முகப்பிற்குச் செல்லவும்',
    'donor.title': 'நன்கொடையாளர் டாஷ்போர்டு',
    'donor.subtitle': 'உங்கள் தாக்கத்தைக் கண்காணித்து உங்கள் நன்கொடைகளை நிர்வகிக்கவும்',
    'donor.donate': 'மருந்து தானம் செய்',
    'donor.history': 'நன்கொடை வரலாறு',
    'donor.impact': 'உங்கள் தாக்கம்',
    'donor.saved': 'சேமிக்கப்பட்ட மருந்துகள்',
    'donor.lives': 'பாதிக்கப்பட்ட உயிர்கள்',
    'donor.points': 'பெற்ற மெட்பாயிண்ட்ஸ்',
    'receiver.title': 'கோரிக்கை மையம்',
    'receiver.subtitle': 'தேவைப்படுபவர்களுக்கு சரிபார்க்கப்பட்ட மருந்து உபரி கிடைக்கிறது.',
    'receiver.newRequest': 'புதிய மருந்து கோரிக்கை',
    'receiver.log': 'உங்கள் சுகாதார பதிவு',
    'receiver.ayushman': 'ஆயுஷ்மான் ஐடியை சரிபார்க்கவும்',
    'receiver.ayushmanPlaceholder': 'ஆயுஷ்மான் ஐடியை உள்ளிடவும் (எ.கா. ABC)',
    'receiver.validate': 'கணக்கை சரிபார்க்கவும்',
    'receiver.invalidId': 'தவறான ஆயுஷ்மான் ஐடி. முன்மாதிரி உருவகப்படுத்துதலுக்கு "ABC" ஐப் பயன்படுத்தவும்.',
    'receiver.uploadPrescription': 'மருந்துச் சீட்டைப் பதிவேற்றவும்',
    'receiver.prescriptionDesc': 'சரிபார்ப்பிற்காக உங்கள் மருத்துவ மருந்துச் சீட்டைப் பதிவேற்றவும்.',
    'receiver.verifying': 'மருந்துச் சீட்டு சரிபார்க்கப்படுகிறது...',
    'receiver.verified': 'சரிபார்க்கப்பட்ட மருந்துச் சீட்டு',
    'receiver.verifiedDesc': 'உங்கள் மருந்துச் சீட்டு சரிபார்க்கப்பட்டது. நீங்கள் இப்போது விநியோகத்தைத் திட்டமிடலாம்.',
    'receiver.schedule': 'விநியோகத்தைத் திட்டமிடுங்கள்',
    'receiver.scheduling': 'விநியோகம் திட்டமிடப்படுகிறது...',
    'receiver.scheduled': 'விநியோகம் திட்டமிடப்பட்டது',
    'receiver.arrival': 'மதிப்பிடப்பட்ட வருகை',
    'receiver.otp': 'விநியோக OTP',
    'receiver.otpDesc': 'இந்த OTP ஐ விநியோக கூட்டாளரிடம் காட்டவும்.',
    'receiver.history': 'முந்தைய கோரிக்கைகள்',
    'receiver.status.uploaded': 'மருந்துச் சீட்டு பதிவேற்றப்பட்டது',
    'receiver.status.verified': 'சரிபார்க்கப்பட்ட மருந்துச் சீட்டு',
    'receiver.status.scheduled': 'விநியோகம் திட்டமிடப்பட்டது',
    'receiver.status.completed': 'முடிந்தது'
  },
  [Language.MARATHI]: {
    'nav.home': 'होम',
    'nav.donate': 'दान करा',
    'nav.request': 'विनंती',
    'nav.ngo': 'एनजीओ पोर्टल',
    'nav.gov': 'प्रशासक',
    'nav.about': 'बद्दल',
    'nav.translate': 'अनुवाद',
    'nav.signin': 'साइन इन',
    'nav.getstarted': 'सुरू करा',
    'nav.logout': 'लॉगआउट',
    'hero.badge': 'स्मार्ट औषध पुनर्वितरण नेटवर्क',
    'hero.title': 'न वापरलेल्या औषधांचे जीवनरक्षक संसाधनांमध्ये रूपांतर करणे',
    'hero.desc': 'फार्मास्युटिकल कचरा कमी करण्यासाठी, जीव वाचवण्यासाठी आणि बुद्धिमान औषध पुनर्वितरणाद्वारे शाश्वत आरोग्य सेवा परिसंस्था तयार करण्यासाठी आमच्या नेटवर्कमध्ये सामील व्हा.',
    'hero.donate': 'औषध दान करा',
    'hero.request': 'औषधांची विनंती करा',
    'hero.partner': 'भागीदार व्हा',
    'stats.saved': 'वाचवलेली औषधे (युनिट्स)',
    'stats.lives': 'प्रभावित जीवन',
    'stats.co2': 'CO₂ कमी झाले (किलो)',
    'stats.waste': 'टाळलेला कचरा (₹)',
    'map.title': 'थेट औषध वितरण नेटवर्क',
    'map.desc': 'शहरभर रिअल-टाइम औषध प्रवाह, ड्रॉप-बॉक्स ठिकाणे आणि सक्रिय वितरण मार्ग ट्रॅक करा',
    'map.dropbox': 'ड्रॉप-बॉक्स ठिकाणे',
    'map.routes': 'सक्रिय मार्ग',
    'map.delivered': 'आज वितरित',
    'how.title': 'हे कसे कार्य करते',
    'how.desc': 'तीन चरणांमध्ये सोपे, पारदर्शक आणि कार्यक्षम औषध पुनर्वितरण',
    'how.step1.title': 'संकलन',
    'how.step1.desc': 'दाते न वापरलेली औषधे सत्यापित संकलन केंद्रांवर सोडतात किंवा होम पिकअप शेड्यूल करतात. प्रत्येक देणगीचा मागोवा घेतला जातो आणि नोंद केली जाते.',
    'how.step2.title': 'सत्यापन',
    'how.step2.desc': 'आमचे परवानाधारक फार्मासिस्ट आणि सत्यापित प्रणाली पूर्ण सुरक्षा आणि सत्यता सुनिश्चित करण्यासाठी प्रत्येक बॅचवर कठोर क्लिनिकल ऑडिट करतात.',
    'how.step3.title': 'पुनर्निर्देशन',
    'how.step3.desc': 'आमच्या सुरक्षित लॉजिस्टिक नेटवर्कद्वारे सत्यापित एनजीओ, दवाखाने आणि गरजू रुग्णांना औषधे पुनर्वितरित केली जातात.',
    'cta.title': 'जीवनरक्षक ग्रिडमध्ये सामील व्हा',
    'cta.desc': 'औषधे वाया जाऊ देऊ नका. सर्वांसाठी आरोग्य सेवा सुलभ करणाऱ्या हजारो लोकांमध्ये सामील व्हा.',
    'cta.start': 'आता दान करण्यास सुरुवात करा',
    'cta.learn': 'अधिक जाणून घ्या',
    'auth.welcome': 'पुन्हा स्वागत आहे!',
    'auth.join': 'ग्रिडमध्ये सामील व्हा',
    'auth.loginDesc': 'आमच्याशी जोडलेले राहण्यासाठी कृपया तुमच्या वैयक्तिक माहितीसह लॉगिन करा',
    'auth.regDesc': 'तुमचा वैयक्तिक तपशील प्रविष्ट करा और आमच्यासह प्रवास सुरू करा',
    'auth.create': 'खाते तयार करा',
    'auth.signin': 'साइन इन',
    'auth.signup': 'साइन अप',
    'auth.google': 'गूगलसह साइन इन करा',
    'auth.emailOr': 'किंवा ईमेल वापरा',
    'auth.login': 'लॉगिन',
    'auth.registration': 'नोंदणी',
    'auth.identity': 'ओळख निवडा',
    'auth.email': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.remember': 'माझी आठवण ठेवा',
    'auth.forgot': 'पासवर्ड विसरलात?',
    'auth.back': 'होमवर परत जा',
    'donor.title': 'दाता डॅशबोर्ड',
    'donor.subtitle': 'तुमच्या प्रभावाचा मागोवा घ्या आणि तुमच्या देणग्या व्यवस्थापित करा',
    'donor.donate': 'औषध दान करा',
    'donor.history': 'देणगी इतिहास',
    'donor.impact': 'तुमचा प्रभाव',
    'donor.saved': 'वाचवलेली औषधे',
    'donor.lives': 'प्रभावित जीवन',
    'donor.points': 'मेडपॉइंट्स मिळवले',
    'receiver.title': 'विनंती केंद्र',
    'receiver.subtitle': 'गरजू लोकांसाठी सत्यापित फार्मास्युटिकल अधिशेष उपलब्ध आहे.',
    'receiver.newRequest': 'नवीन औषध विनंती',
    'receiver.log': 'तुमचा आरोग्य लॉग',
    'receiver.ayushman': 'आयुष्मान आयडी सत्यापित करा',
    'receiver.ayushmanPlaceholder': 'आयुष्मान आयडी प्रविष्ट करा (उदा. ABC)',
    'receiver.validate': 'खाते सत्यापित करा',
    'receiver.invalidId': 'अवैध आयुष्मान आयडी. कृपया प्रोटोटाइप सिम्युलेशनसाठी "ABC" वापरा.',
    'receiver.uploadPrescription': 'प्रिस्क्रिप्शन अपलोड करा',
    'receiver.prescriptionDesc': 'कृपया सत्यापनासाठी तुमचे मेडिकल प्रिस्क्रिप्शन अपलोड करा.',
    'receiver.verifying': 'प्रिस्क्रिप्शन सत्यापित केले जात आहे...',
    'receiver.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.verifiedDesc': 'तुमचे प्रिस्क्रिप्शन सत्यापित झाले आहे. तुम्ही आता डिलिव्हरी शेड्यूल करू शकता.',
    'receiver.schedule': 'डिलिव्हरी शेड्यूल करा',
    'receiver.scheduling': 'डिलिव्हरी शेड्यूल केली जात आहे...',
    'receiver.scheduled': 'डिलिव्हरी शेड्यूल केली',
    'receiver.arrival': 'अंदाजित आगमन',
    'receiver.otp': 'डिलिव्हरी ओटीपी',
    'receiver.otpDesc': 'डिलिव्हरी पार्टनरला हा ओटीपी दाखवा.',
    'receiver.history': 'मागील विनंत्या',
    'receiver.status.uploaded': 'प्रिस्क्रिप्शन अपलोड केले',
    'receiver.status.verified': 'सत्यापित प्रिस्क्रिप्शन',
    'receiver.status.scheduled': 'डिलिव्हरी शेड्यूल केली',
    'receiver.status.completed': 'पूर्ण झाले'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(Language.ENGLISH);

  const t = (key: string): string => {
    return translations[language][key] || translations[Language.ENGLISH][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
